version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "uv"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
