['AFK Stages']
Attempts = 1
Formations = 4
'Run Manual Formations Last' = true
'Skip Manual Formations' = false
'Spend Gold' = true
'Start with current Formation' = false
'Suggested Formations' = true

['Arcane Labyrinth']
Difficulty = 13
'Key Quota' = 2700

['Claim AFK Rewards']
'Claim Stage Rewards' = true

['Custom Routine 1']
'Display Name' = ''
Repeat = true
'Task List' = []

['Custom Routine 2']
'Display Name' = ''
Repeat = true
'Task List' = []

['Custom Routine 3']
'Display Name' = ''
Repeat = true
'Task List' = []

[Dailies]
'Arena Battle' = true
'Buy All Affinity' = true
'Buy Discount Affinity' = true
'Buy Temporal Essences' = false
'Essence Buy Count' = 1
'Single Pull' = false

['Dream Realm']
'Spend Gold' = true

["Dura's Trials"]
Attempts = 5
Formations = 10
'Spend Gold' = true
'Start with current Formation' = false
'Suggested Formations' = true

[General]
'Assist Limit' = 10
'Exclude Heroes' = []

['Legend Trial']
Attempts = 5
Formations = 10
'Run Manual Formations Last' = true
'Skip Manual Formations' = false
'Spend Gold' = true
'Start with current Formation' = false
'Suggested Formations' = true
Towers = ['Lightbearer', 'Wilder', 'Graveborn', 'Mauler']

['Titan Reaver Proxy Battles']
'Titan Reaver Proxy Battle Limit' = 50
