[book]
authors = ["AdbAutoPlayer"]
language = "en"
src = "src"
title = "AdbAutoPlayer Documentation"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/AdbAutoPlayer/AdbAutoPlayer"
edit-url-template = "https://github.com/AdbAutoPlayer/AdbAutoPlayer/edit/main/docs/{path}"

[preprocessor.alerts]
