# See:
# - <https://github.com/tauri-apps/tauri-action>
# - <https://pytauri.github.io/pytauri/latest/usage/tutorial/build-standalone/>

name: "publish"

on:
  workflow_dispatch:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  publish-tauri:
    permissions:
      contents: write # required for creating github releases
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-14" # for Intel based macs.
          #   target: "x86_64-apple-darwin"
          #   config: "src-tauri/tauri.bundle.json"
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            target: "aarch64-apple-darwin"
            config: "src-tauri/tauri.bundle.json"
          # - platform: "ubuntu-22.04"
          #   target: "x86_64-unknown-linux-gnu"
          #   config: "src-tauri/tauri.bundle.json"
          # - platform: "ubuntu-22.04-arm"
          #   target: "aarch64-unknown-linux-gnu"
          #   config: "src-tauri/tauri.bundle.json"
          - platform: "windows-latest"
            target: "x86_64-pc-windows-msvc"
            config: "src-tauri/tauri.bundle.windows.json"
          # - platform: "windows-11-arm"
          #   target: "aarch64-pc-windows-msvc"
          #  config: "src-tauri/tauri.bundle.json"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies (ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          # version-file: "pyproject.toml"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"
          cache: "pnpm"

      - run: pnpm install

      # See:
      # - <https://github.com/astral-sh/python-build-standalone/releases>
      # - <https://raw.githubusercontent.com/astral-sh/python-build-standalone/latest-release/latest-release.json>
      # - <https://gregoryszorc.com/docs/python-build-standalone/main/running.html#obtaining-distributions>
      - name: Download python-build-standalone
        env:
          PYTHON_VERSION: "3.13.9"
          TAG: "20251031"
          TARGET: ${{ matrix.target }}
        run: |
          url="https://github.com/astral-sh/python-build-standalone/releases/download/${TAG}/cpython-${PYTHON_VERSION}+${TAG}-${TARGET}-install_only_stripped.tar.gz"
          DEST_DIR="src-tauri/pyembed"

          mkdir "$DEST_DIR"
          curl -L "$url" | tar -xz -C "$DEST_DIR"

          # ref: <https://github.com/pytauri/pytauri/issues/99#issuecomment-2704556726>
          if [[ "${{ runner.os }}" == "macOS" ]]; then
              python_major_minor="${PYTHON_VERSION%.*}"  # "3.13.7" -> "3.13"
              install_name_tool -id "@rpath/libpython${python_major_minor}.dylib" "$DEST_DIR/python/lib/libpython${python_major_minor}.dylib"
          fi

      - name: Install the project into the embedded python environment
        env:
          PYTAURI_STANDALONE: 1
          PYTHON_PATH: ${{ runner.os == 'Windows' && './src-tauri/pyembed/python/python.exe' || './src-tauri/pyembed/python/bin/python3' }}
        run: |
          uv pip install \
              --exact \
              --compile-bytecode \
              --python=${{ env.PYTHON_PATH }} \
              ./src-tauri

      # Set build environment variables, see:
      # <https://pytauri.github.io/pytauri/latest/usage/tutorial/build-standalone/#build-and-bundle>

      - name: Set build environment variables (windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $PYO3_PYTHON = (Resolve-Path -LiteralPath ".\src-tauri\pyembed\python\python.exe").Path
          echo "PYO3_PYTHON=$PYO3_PYTHON" >> $env:GITHUB_ENV

      - name: Set build environment variables (linux)
        if: runner.os == 'Linux'
        shell: bash
        env:
          # `adb-auto-player` is your app `productName` in `tauri.conf.json`
          PRODUCT_NAME: "AdbAutoPlayer"
        run: |
          PYO3_PYTHON=$(realpath ./src-tauri/pyembed/python/bin/python3)
          RUSTFLAGS=" \
            -C link-arg=-Wl,-rpath,\$ORIGIN/../lib/$PRODUCT_NAME/lib \
            -L $(realpath ./src-tauri/pyembed/python/lib)"

          echo "PYO3_PYTHON=$PYO3_PYTHON" >> $GITHUB_ENV
          echo "RUSTFLAGS=$RUSTFLAGS" >> $GITHUB_ENV

      - name: Set build environment variables (macos)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          PYO3_PYTHON=$(realpath ./src-tauri/pyembed/python/bin/python3)
          RUSTFLAGS=" \
            -C link-arg=-Wl,-rpath,@executable_path/../Resources/lib \
            -L $(realpath ./src-tauri/pyembed/python/lib)"

          echo "PYO3_PYTHON=$PYO3_PYTHON" >> $GITHUB_ENV
          echo "RUSTFLAGS=$RUSTFLAGS" >> $GITHUB_ENV

      - run: pnpm set-version ${{ github.event.release.tag_name }}
        if: github.event_name == 'release'

      - name: Build and bundle the app
        if: github.event_name == 'release'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.event.release.tag_name }}
          releaseName: ${{ github.event.release.tag_name }}
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          includeDebug: false
          args: '--target ${{ matrix.target }} --config ${{ matrix.config }} --config src-tauri/tauri.bundle.templates.json --verbose'


      - name: Upload macOS important readme to release
        if: github.event_name == 'release' && runner.os == 'macOS'
        uses: softprops/action-gh-release@v2
        with:
          files: scripts/macos/MACOS_READ_THIS_IMPORTANT.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: tauri-apps/tauri-action@v0
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          includeDebug: true
          args: '--target ${{ matrix.target }} --config ${{ matrix.config }} --verbose'

      - name: Upload test build artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/bundle/
